POST HTTP://LOCALHOST:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoZXJwYSIsImlkIjoiNjU1MjI3YWMwNmI1NjhkNzExNjE0MDQxIiwiaWF0IjoxNzAwNTg5MDc4fQ.wG5T99-8AkBW5SZdw3JrpBukXUutHYBhkHMWplwz4rw

{
  "title": "Ninth blog",
  "author": "Someone who is a sicko",
  "url": "localhost:3001",
  "likes": "15"
}